version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ./awsdotcore/awsdotcore.csproj
  build:
    commands:
      - nuget restore
      - msbuild ./awsdotcore/awsdotcore.csproj /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /p:OutDir=C:\Work\dotnet\vidro\ /t:Package
      - cp  ./awsdotcore/aws-windows-deployment-manifest.json  ./awsdotcore/staging/
artifacts:
  files:
    - '**/*'
  base-directory: C:\Work\dotnet\vidro\AWSBeanstalkHelloWorld\AWSBeanstalkHelloWorldWebApp\obj\Release\Package\PackageTmp\'
    
